name: chemprop

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.7,<3.9
  - flask>=1.1.2,<=2.1.3
  - Werkzeug<3
  - gunicorn>=20.0.4
  - hyperopt>=0.2.3
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pandas-flavor>=0.2.0
  - pip>=20.0.2
  - pytorch>=1.4.0
  - rdkit>=2020.03.1.0
  - scikit-learn>=0.22.2.post1
  - scipy>=1.4.1
  - tensorboardX>=2.0
  - torchvision>=0.5.0
  - tqdm>=4.45.0
  - sphinx-rtd-theme>=2.0.0
  - pip:
      - typed-argument-parser>=1.6.1
      - git+https://github.com/bp-kelley/descriptastorus
